### PR TITLE
Device Control Overhaul with stepless Sliders and more colors.

### PR DESCRIPTION
**Pull request by MrMatch246**
Recolored DeviceControl for more Contrast, each column can have a different color.

### CODE REVIEW

**Comment by MrMatch246** [comment]
When in device control view, press right bottom button to toggle stepless sliders

**Comment by hdavid** [comment]
Hi this is very interesting !


i gave it a try and it seems to work, i am happy you found a way that does not crash live.
i did not look at the code in details yet.

some comments: 
- the logging does not work on macos we could maybe remove it if no longer needed ?
- this import has an extra leading dot. https://github.com/MrMatch246/Launchpad95/blob/master/DeviceControllerComponent.py#L1
- i am not a big fan of the new colours for the sliders. it bring more visual complexity and personnally did not helped me at all to know which slider was what. could we revert back to the old colours scheme, or make it an options in Settings.py ?
- the step less mode is put back off when switching between modes (instrument mode for instance)
- if i start moving a fader slowly and switch mode, the fader stops. do you think it's fixable ? 

and some questions:
- the stepless mode is so cool, why not make it on by default (and restore the 4th snapshot but)
-  do you think we could apply it the mixer mode ?

**Comment by hdavid** [comment]
i am not sure if you know but you can trace errors in the ableton log file. on macos:
tail -f ~/Library/Preferences/Ableton/*/Log.txt

**Comment by hdavid** [comment]
two more things i noticed: 
- the OSD max for live device does not work anymore (i fixed), but anyhow it seems the code (around line 166 in device controller) does not work, it return "function partial .... " instead of the expected value.

- while paging thru device parmaters pages, the launchpad gets messed up somehow. pressing the buttons fixes it. i tried with EQ8.
-

**Comment by MrMatch246** [comment]
- Regarding the logging, this should be fine as it is disabled by default and if someone (like me) needs it they can enable it and see whats going on without having to reinsert the log statements etc. maybe i can also fix it for macos.
- Ah thanks! I missed that one. I played around with the idea of patching the framework.
- I am sure we could make it a setting. Me personally i had the same feeling towards the monocolor slider.
- When i switch modes the stepless mode keeps staying on?
- yes it is , noted

- I made it optional in case someone wants to "wipe" all params (like going from left to right on top or bottom row), im not sure how often this is the case but we would loose this feature. maybe there is some common ground with having some special press just to make all params zero. but ultimately this needs more feedback. (i dont think im knowledgeable enought with the Launchpad community as i just got it a week ago :D)
- Im still unsure about how the value stuff should work in the end regarding velocity to speed. but i think it would make sense to add a version that does this stuff properly for people without velocity.
- Regarding mixer mode, i would think so yes. The core concept is easy enough so i can take a look at is.

**Comment by MrMatch246** [comment]
> i am not sure if you know but you can trace errors in the ableton log file. on macos: tail -f ~/Library/Preferences/Ableton/*/Log.txt

which print/log statements print there? cause in this case i certainly can remove my custom logging that does exactly the same thing :D

**Comment by MrMatch246** [comment]
> * the OSD max for live device does not work anymore (i fixed, attached here), but anyhow it seems the code (around line 166 in device controller) does not work, it return "function partial .... " instead of the expected value.

As the OSD device never worked for me, i didnt bother looking into it and if something needs adaptation. 
but i think i have a hunch what happened there.

> * while paging thru device parmaters pages, the launchpad gets messed up somehow. pressing the buttons fixes it. i tried with EQ8.
> 

What kind of messed up are we talking about? the first EQ8 bank is on off switches which indeed bug around probably because they arent the normal value range thingy

**Comment by MrMatch246** [comment]
> [Launchpad95Helper.amxd.zip](https://github.com/hdavid/Launchpad95/files/12342802/Launchpad95Helper.amxd.zip)
2023-08-16T00:00:35.573032: error: Message from Max: js: Launchpad95 not found!
2023-08-16T00:00:35.573061: error: Message from Max: js:
2023-08-16T00:00:35.573927: error: Message from Max: js: L95.js: Javascript TypeError: l95_osd is null line 25
2023-08-16T00:00:35.573961: error: Message from Max: js: error calling function bang [L95.js]
Thats what you meant?

**Comment by MrMatch246** [comment]
> * the OSD max for live device does not work anymore (i fixed, attached here), but anyhow it seems the code (around line 166 in device controller) does not work, it return "function partial .... " instead of the expected value.

Okay this is fixed for now, but this problem will arise whenever one wants to access any attribute of the strip by the object.attribute notation. this needs to be fixed then by adding cases to the proxy and server.

**Comment by MrMatch246** [comment]
Ableton crashes now when changing track while in device control mode

**Comment by MrMatch246** [comment]
Fixed these issues now. OSD probably still doesnt work tho

**Comment by MrMatch246** [comment]
> * i am not a big fan of the new colours for the sliders. it bring more visual complexity and personnally did not helped me at all to know which slider was what. could we revert back to the old colours scheme, or make it an options in Settings.py ?

Fixed now, custom mode can be enabled in the settings

**Comment by hdavid** [comment]
thanks for all the fixes. it is starting to take shape!
 for the osd m4l device, i am not sure what is going on yes.  normally the version i shared earlier does not have this issue with the missing js script.

about the script in general, while i love the idea, it seems ableton does not like so much this kind of tricks. initiating a slider fade and switch track, ableton freezes. do think we can reach a stable solution ? 
i am fine to keep it in the main branch, as long as user must enable the feature in settings.py, and we can put a little disclaimer there.

About the OSD M4l , it seems that the device controller mode is no always on, and i only get osd about device controller mode. all the time. other modes are gone. any idea ?

**Comment by hdavid** [comment]
oh and i pushed a fix for logging and colours for non RGB launchpad.

also about your question for launchpad with no velocity, i think, but to be double check, send a velocity of 100. (if not then maybe 127)

**Comment by MrMatch246** [comment]
> thanks for all the fixes. it is starting to take shape! for the osd m4l device, i am not sure what is going on yes. normally the version i shared earlier does not have this issue with the missing js script.

It would be nice if you could fix it or help me debugging because im not better than guessing with this.

> about the script in general, while i love the idea, it seems ableton does not like so much this kind of tricks. initiating a slider fade and switch track, ableton freezes. do think we can reach a stable solution ? i am fine to keep it in the main branch, as long as user must enable the feature in settings.py, and we can put a little disclaimer there.

Freezes in most cases regarding these scripts are all basically boiling down to some call taking long to return. Either some failing get on a queue, an while true loop that doesnt exit (or lot of prints during debugging)
My current state works with switching tracks, devices and banks big and small enums.
Only bug that i see left over is the leds glitching when switching to instruments from device controller
Push coming asap

> 
> About the OSD M4l , it seems that the device controller mode is no always on, and i only get osd about device controller mode. all the time. other modes are gone. any idea ?

Can you repeat this? btw ich spreche auch deutsch :D
But no i have no idea. as it never worked for me in the first place i only touched some of it now to fix another unrelated bug

**Comment by MrMatch246** [comment]
@hdavid This should have fixed the gui bugs, please let me now if there are any other bugs i havent seen any apart from the OSD M4L stuff

**Comment by hdavid** [comment]
hi, thanks for the fixes. i will have a look this week :) 
if you want to can talk on slack: https://join.slack.com/t/launchpad95/shared_invite/zt-21y02uqds-1AyN~OXfc_7TwgqO3mKVCA

**Comment by hdavid** [comment]
thanks for all the work ! :)

**Pull request merged**
